// Example 3: TypeScript Configuration
// Demonstrates TypeScript configuration for Next.js

// ============================================
// Example 1: Basic TypeScript Configuration
// File: tsconfig.json
// ============================================

const basicTsConfig = {
  compilerOptions: {
    target: 'ES2020',
    lib: ['dom', 'dom.iterable', 'esnext'],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    forceConsistentCasingInFileNames: true,
    noEmit: true,
    esModuleInterop: true,
    module: 'esnext',
    moduleResolution: 'bundler',
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: 'preserve',
    incremental: true,
    plugins: [
      {
        name: 'next',
      },
    ],
  },
  include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
  exclude: ['node_modules'],
}

// ============================================
// Example 2: Path Aliases Configuration
// File: tsconfig.json
// ============================================

const pathAliasesConfig = {
  compilerOptions: {
    target: 'ES2020',
    lib: ['dom', 'dom.iterable', 'esnext'],
    allowJs: true,
    skipLibCheck: true,
    strict: true,
    forceConsistentCasingInFileNames: true,
    noEmit: true,
    esModuleInterop: true,
    module: 'esnext',
    moduleResolution: 'bundler',
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: 'preserve',
    incremental: true,
    plugins: [
      {
        name: 'next',
      },
    ],
    // Path aliases for cleaner imports
    baseUrl: '.',
    paths: {
      '@/*': ['./*'],
      '@/components/*': ['./components/*'],
      '@/utils/*': ['./utils/*'],
      '@/lib/*': ['./lib/*'],
      '@/types/*': ['./types/*'],
      '@/hooks/*': ['./hooks/*'],
      '@/styles/*': ['./styles/*'],
    },
  },
  include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
  exclude: ['node_modules'],
}

// ============================================
// Example 3: Strict TypeScript Configuration
// File: tsconfig.json
// ============================================

const strictTsConfig = {
  compilerOptions: {
    target: 'ES2020',
    lib: ['dom', 'dom.iterable', 'esnext'],
    allowJs: true,
    skipLibCheck: true,
    
    // Strict type checking
    strict: true,
    noImplicitAny: true,
    strictNullChecks: true,
    strictFunctionTypes: true,
    strictBindCallApply: true,
    strictPropertyInitialization: true,
    noImplicitThis: true,
    alwaysStrict: true,
    
    // Additional checks
    noUnusedLocals: true,
    noUnusedParameters: true,
    noImplicitReturns: true,
    noFallthroughCasesInSwitch: true,
    noUncheckedIndexedAccess: true,
    
    forceConsistentCasingInFileNames: true,
    noEmit: true,
    esModuleInterop: true,
    module: 'esnext',
    moduleResolution: 'bundler',
    resolveJsonModule: true,
    isolatedModules: true,
    jsx: 'preserve',
    incremental: true,
    plugins: [
      {
        name: 'next',
      },
    ],
    baseUrl: '.',
    paths: {
      '@/*': ['./*'],
    },
  },
  include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
  exclude: ['node_modules'],
}

// ============================================
// Example 4: Type Definitions
// File: types/global.d.ts
// ============================================

// Global type definitions
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      NEXT_PUBLIC_API_URL: string
      DATABASE_URL: string
      SECRET_KEY: string
    }
  }
}

// Custom type definitions
interface Window {
  gtag?: (...args: any[]) => void
  dataLayer?: any[]
}

// Module declarations
declare module '*.svg' {
  import React from 'react'
  const SVG: React.VFC<React.SVGProps<SVGSVGElement>>
  export default SVG
}

declare module '*.md' {
  const content: string
  export default content
}

export {}

// ============================================
// Example 5: Next.js Type Configuration
// File: next-env.d.ts
// ============================================

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// It is automatically generated by Next.js

// ============================================
// Example 6: Component Props Types
// File: types/components.ts
// ============================================

import { ReactNode } from 'react'

export interface ButtonProps {
  children: ReactNode
  onClick?: () => void
  variant?: 'primary' | 'secondary'
  disabled?: boolean
}

export interface CardProps {
  title: string
  description?: string
  children?: ReactNode
  className?: string
}

export interface FormFieldProps {
  label: string
  name: string
  type?: string
  required?: boolean
  error?: string
}

// ============================================
// Example 7: API Response Types
// File: types/api.ts
// ============================================

export interface ApiResponse<T = any> {
  success: boolean
  data?: T
  error?: string
  message?: string
}

export interface PaginatedResponse<T> {
  data: T[]
  pagination: {
    page: number
    limit: number
    total: number
    totalPages: number
  }
}

export interface User {
  id: string
  name: string
  email: string
  createdAt: string
}

export interface Post {
  id: string
  title: string
  content: string
  authorId: string
  createdAt: string
}

